# ######## Window rules ########
#widgetrule below all others desktop
windowrulev3 = float, title:AIMaster
windowrulev3 = float,onworkspace:all,layer:desktop,decorations:off,shadow:off,class:^desktop-widget$
# Uncomment to apply global transparency to all windows:
#windowrulev3 = opacity 0.1, tag:kitty
windowrulev3 = opacity 1 override 1 override 1 override, title:.*
windowrulev3 = noblur, xwayland:1, class:^(?!kitty$).*
# Floating
windowrulev3 = float, class:^(blueberry\.py)$
#windowrulev3 = float, class:^(steam)$
windowrulev3 = float, class:^(guifetch)$   # FlafyDev/guifetch
windowrulev3 = float, class:^(pavucontrol)$
windowrulev3 = size 45%, class:^(pavucontrol)$
windowrulev3 = center, class:^(pavucontrol)$
windowrulev3 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev3 = size 45%, class:^(org.pulseaudio.pavucontrol)$
windowrulev3 = center, class:^(org.pulseaudio.pavucontrol)$
windowrulev3 = float, class:^(nm-connection-editor)$
windowrulev3 = size 45%, class:^(nm-connection-editor)$
windowrulev3 = center, class:^(nm-connection-editor)$
#windowrulev3 = stayfocused, title:^()$,class:^(steam)$
#windowrulev3 = minsize 1 1, title:^()$,class:^(steam)$
# Tiling
windowrulev3 = tile, class:^dev\.warp\.Warp$

# Picture-in-Picture
windowrulev3 = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrulev3 = keepaspectratio, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrulev3 = move 73% 72%, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrulev3 = size 25%, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrulev3 = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrulev3 = pin, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$

# Dialog windows – float+center these windows.
windowrulev3 = center, title:^(Open File)(.*)$
windowrulev3 = center, title:^(Select a File)(.*)$
windowrulev3 = center, title:^(Choose wallpaper)(.*)$
windowrulev3 = center, title:^(Open Folder)(.*)$
windowrulev3 = center, title:^(Save As)(.*)$
windowrulev3 = center, title:^(Library)(.*)$
windowrulev3 = center, title:^(File Upload)(.*)$
windowrulev3 = float, title:^(Open File)(.*)$
windowrulev3 = float, title:^(Select a File)(.*)$
windowrulev3 = float, title:^(Choose wallpaper)(.*)$
windowrulev3 = float, title:^(Open Folder)(.*)$
windowrulev3 = float, title:^(Save As)(.*)$
windowrulev3 = float, title:^(Library)(.*)$
windowrulev3 = float, title:^(File Upload)(.*)$


# Dolphin file dialogs
windowrulev3 = float, class:^(org.kde.dolphin)$, title:^(Open|Save|Select|Choose)(.*)$
windowrulev3 = stayfocused, class:^(org.kde.dolphin)$, title:^(Open|Save|Select|Choose)(.*)$
windowrulev3 = pin, class:^(org.kde.dolphin)$, title:^(Open|Save|Select|Choose)(.*)$

# Thunar file dialogs
windowrulev3 = float, class:^(Thunar)$, title:^(Open|Save|Select|Choose)(.*)$
windowrulev3 = stayfocused, class:^(Thunar)$, title:^(Open|Save|Select|Choose)(.*)$
windowrulev3 = pin, class:^(Thunar)$, title:^(Open|Save|Select|Choose)(.*)$
# --- Tearing ---
windowrulev3 = immediate, title:.*\.exe
windowrulev3 = immediate, class:^(steam_app)

# No shadow for tiled windows (matches windows that are not floating).
windowrulev3 = noshadow, floating:0

# ######## Workspace rules ########
workspace = special:special, gapsout:100, gapsin:10
workspace = special:special2, gapsout:100, gapsin:10
workspace = special:special3, gapsout:100, gapsin:10
workspace = special:special4, gapsout:100, gapsin:10
workspace = special:special5, gapsout:100, gapsin:10
workspace = special:special6, gapsout:100, gapsin:10
workspace = special:special7, gapsout:100, gapsin:10
workspace = special:special8, gapsout:100, gapsin:10
workspace = special:special9, gapsout:100, gapsin:10
workspace = special:special99, gapsout:200, gapsin:10
